# Generated by Django 4.2.11 on 2024-05-03 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('SERIALNUM', models.IntegerField(primary_key=True, serialize=False)),
                ('MANUFACTURER', models.CharField(max_length=10)),
                ('MODEL', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('CITYCODE', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('CITYNAME', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('FLIGHTNUM', models.IntegerField(primary_key=True, serialize=False)),
                ('DEPTIME', models.DateTimeField()),
                ('ARRTIME', models.DateTimeField()),
                ('DESTCITYCODE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_flights', to='website.city')),
                ('ORIGINCITYCODE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_flights', to='website.city')),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('PASSENGERNUM', models.IntegerField(primary_key=True, serialize=False)),
                ('SURNAME', models.CharField(max_length=30)),
                ('NAME', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('EMPNUM', models.IntegerField(primary_key=True, serialize=False)),
                ('SURNAME', models.CharField(max_length=30)),
                ('NAME', models.CharField(max_length=20)),
                ('SALARY', models.DecimalField(decimal_places=2, max_digits=10)),
                ('TYPE', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Stretch',
            fields=[
                ('STRETCHNUM', models.IntegerField(primary_key=True, serialize=False)),
                ('ARRTIME', models.DateTimeField()),
                ('DEPTIME', models.DateTimeField()),
                ('DESTCITYCODE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_stretches', to='website.city')),
                ('FLIGHTNUM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.flight')),
                ('ORIGINCITYCODE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_stretches', to='website.city')),
            ],
        ),
        migrations.CreateModel(
            name='StaffPhone',
            fields=[
                ('PHONE', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('EMPNUM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('PILOTNUM', models.IntegerField(primary_key=True, serialize=False)),
                ('EMPNUM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.staff')),
            ],
        ),
        migrations.CreateModel(
            name='PassengerPhone',
            fields=[
                ('PHONE', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('PASSENGERNUM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.passenger')),
            ],
        ),
        migrations.AddField(
            model_name='flight',
            name='PILOTNUM',
            field=models.ForeignKey(limit_choices_to={'TYPE'}, on_delete=django.db.models.deletion.CASCADE, related_name='pilot_flights', to='website.pilot'),
        ),
        migrations.AddField(
            model_name='flight',
            name='PLANENUM',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airplane_flights', to='website.airplane'),
        ),
        migrations.CreateModel(
            name='StaffAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ADDRESSDETAILS', models.CharField(max_length=50)),
                ('EMPNUM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.staff')),
            ],
            options={
                'unique_together': {('EMPNUM', 'ADDRESSDETAILS')},
            },
        ),
        migrations.CreateModel(
            name='PilotTypeRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TYPERATING', models.CharField(max_length=20)),
                ('DATEEARNED', models.DateTimeField()),
                ('PILOTNUM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.pilot')),
            ],
            options={
                'unique_together': {('TYPERATING', 'PILOTNUM')},
            },
        ),
        migrations.CreateModel(
            name='PassengerBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FLIGHTNUM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.flight')),
                ('PASSENGERNUM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.passenger')),
            ],
            options={
                'unique_together': {('PASSENGERNUM', 'FLIGHTNUM')},
            },
        ),
        migrations.CreateModel(
            name='PassengerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ADDRESSDETAILS', models.CharField(max_length=50)),
                ('PASSENGERNUM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.passenger')),
            ],
            options={
                'unique_together': {('PASSENGERNUM', 'ADDRESSDETAILS')},
            },
        ),
        migrations.CreateModel(
            name='FlightCrew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EMPNUM', models.ForeignKey(limit_choices_to={'TYPE': 'Crew'}, on_delete=django.db.models.deletion.CASCADE, to='website.staff')),
                ('FLIGHTNUM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.flight')),
            ],
            options={
                'unique_together': {('FLIGHTNUM', 'EMPNUM')},
            },
        ),
    ]
