# Generated by Django 4.2.11 on 2024-05-16 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StretchDetail',
            fields=[
                ('STRETCHNUM', models.IntegerField(primary_key=True, serialize=False)),
                ('ARRTIME', models.DateTimeField()),
                ('DEPTIME', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='flight',
            name='PILOTNUM',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pilot_flights', to='website.pilot'),
        ),
        migrations.DeleteModel(
            name='Stretch',
        ),
        migrations.AddField(
            model_name='stretchdetail',
            name='FLIGHTNUM',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.flight'),
        ),
        migrations.AddField(
            model_name='stretchdetail',
            name='INTERMEDIATECITYCODE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intermediate_stretch_city', to='website.city'),
        ),
    ]
