# Generated by Django 4.2.11 on 2024-05-16 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_stretchdetail_alter_flight_pilotnum_delete_stretch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stretchdetail',
            name='STRETCHNUM',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
