# Generated by Django 4.2.11 on 2024-05-16 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_stretchdetail_stretchnum'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntermediateCity',
            fields=[
                ('STRETCHNUM', models.AutoField(primary_key=True, serialize=False)),
                ('ARRTIME', models.DateTimeField()),
                ('DEPTIME', models.DateTimeField()),
                ('FLIGHTNUM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.flight')),
                ('INTERMEDIATECITYCODE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intermediate_stretch_city', to='website.city')),
            ],
        ),
        migrations.DeleteModel(
            name='StretchDetail',
        ),
    ]
